# AP 155 Lab Exercise
---
## Exercise 5: Matrices

_Instructions_: 
- **Report figure:** No report figure. Points in the report figure will be allocated to the report discussion 
- **Report discussion:**
  - What were the basis linear equations used to set up the matrix in each question of Problem 2?
  - Once you set up the matrices, what function did you use to solve the matrix equation (Could have different answers)? Check the docstring/documentation/other references and summarize the mechanism behind the function 
- **Code**: Complete the code and ensure it is functional, error-free, readable, and efficient (where needed). Include concise Markdown documentation highlighting the critical steps of your algorithm for each problem.

### Student Information
- _Full Name (Last Name, First Name)_: 
- _Student No._: 20XX-XXXXX
- _Section_: THR-TX-X

### Grading Information (c/o Lab Instructor)
- [Rubrics description link](https://drive.google.com/file/d/1BMSlPot2Mc7XLu0eo4S8I8gLBsIadbCL/view?usp=sharing) (Note: percentages may still be tweaked)

| Criteria | Score | Subtotal |
| --- | --- | --- |
| Report figure | XX | 20 |
| Report discussion | XX | 20|
| Code readability | XX | 20 |
| Code efficiency | XX | 20 | 
| Code appropriateness  | XX | 20 | 
| **TOTAL** | XXX | 100 |

_Date and Time Scored (MM/DD/YYYY HH:MM AM/PM):_:_

---
## Section 1: Report

<!-- ### Report figure

<img src="figures/cat.jpg" alt="Alt text" width=45%> <img src="figures/cat.jpg" alt="Alt text" width=45%>


EDIT ME. See instruction above for what to include. Insert caption here, a short description what the figure illustrates. The syntax in markdown for putting a figure is `![Description](local_file_name.png)` or `<img src="/path/to_image.jpg" alt="Alt text" width=45%>`. Make sure the figure has complete elements.
-->

### Report discussion

EDIT ME. See instruction above for what to include. Insert your discussions here. Discuss your key results with at most 150 words per question.

### Other comments
- EDIT ME
- A self reflection can be placed here.
- This portion is not graded.
- You may insert further questions here.


---
## Section 2: Code

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

### Problem 1: (Circuit Analysis)

Consider a long chain of resistors wired up like this:

<img src="Figures/reschain.png" alt="Alt text" width=95%>

All the resistors have the same resistance~$R$.  The power rail at the top is at voltage~$V_+=5$V.  The problem is to find the voltages $V_1...V_N$ at the internal points in the circuit.

1. **Using Ohm's law and the Kirchhoff current law**, which says that the total net current flow out of (or into) any junction in a circuit must be zero, show that the voltages $V_1\ldots V_N$ satisfy the equations

$$3V_1 - V_2 - V_3 = V_+ $$
$$-V_1 + 4V_2 - V_3 - V_4 = V_+ $$
      
$$-V_{i-2} - V_{i-1} + 4V_i - V_{i+1} - V_{i+2} = 0 $$

$$-V_{N-3} - V_{N-2} + 4V_{N-1} - V_N = V_- = 0 $$
$$-V_{N-2} - V_{N-1} + 3V_N = V_- = 0 $$

Note: The assignment of $V_-$ is to make the equations symmetric

2. Express these equations in vector form~$A\vec{v} = \vec{w}$ and find the values of the matrix~$A$ and the vector~$\vec{w}$.

> We can the equation into vector form by obtaining the coefficient matrix from the system:
> $$
\begin{bmatrix}
  3 & -1 & -1 & 0 & 0 & 0 & 0 & \dots & \dots & 0  \\
  -1 & 4 & -1 & -1 & 0 & 0 & 0 & \dots & \dots & 0 \\
  -1 & -1 & 4 & -1 & -1 & 0 & 0 & \dots & \dots & 0  \\
  0 & -1 & -1 & 4 & -1 & -1 & 0 & \dots & \dots & 0  \\
  \vdots & \vdots & \ddots & \ddots & \ddots & \ddots & \ddots & \ddots & \ddots & \vdots \\
  0 & 0 & 0 & -1 & -1 & 4 & -1 & -1 & 0 & \vdots \\
  \vdots & \vdots & \vdots & \vdots & \ddots & \ddots & \ddots & \ddots & \ddots & \vdots \\
  \vdots & \vdots & \vdots & \vdots & \vdots & \ddots & \ddots & \ddots & \ddots & \vdots \\
  0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & -1 & 3 \\
\end{bmatrix} \begin{bmatrix}
V_1 \\ V_2 \\ V_3 \\ \\ \\  \vdots \\ \\ \\ \\ \\ V_n
\end{bmatrix}
= 
\begin{bmatrix}
V_+ \\ V_+ \\ 0 \\ \\ \\  \vdots \\ \\ \\ \\ \\ 0
\end{bmatrix}
$$

3. Write a program to solve for the values of the~$V_i$ when there are $N=6$ internal junctions with unknown voltages.  (Hint: All the values of $V_i$ should lie between zero and $5$V.  If they don't, something is wrong.)

> For $n = 6$, we have the following system of equations:
$$\begin{matrix}
3V_1& - V_2& - V_3 & & & &= V_+ & \\
-V_1& + 4V_2& - V_3& - V_4 & & &= V_+ & \\
-V_{1}& - V_{2}& + 4V_3& - V_{4}& - V_{5} & &= 0 & \\
&-V_{2}& - V_{3}& + 4V_4& - V_{5}& - V_{6} &= 0 &\\
&&-V_{3}& - V_{4}& + 4V_{5}& - V_6 &= V_- &= 0 \\
&&&-V_{4}& - V_{5}& + 3V_6 &= V_- &= 0
\end{matrix}$$
>
> This is equivalent to the following matrix:
> $$
\begin{bmatrix}
  3 & -1 & -1 & 0 & 0 & 0 \\
  -1 & 4 & -1 & -1 & 0 & 0 \\
  -1 & -1 & 4 & -1 & -1 & 0 \\
  0 & -1 & -1 & 4 & -1 & -1 \\
  0 & 0 & -1 & -1 & 4 & -1 \\
  0 & 0 & 0 & -1 & -1 & 3 \\
\end{bmatrix} \begin{bmatrix}
V_1 \\ V_2 \\ V_3 \\ V_4 \\ V_5 \\ V_6 
\end{bmatrix}
= 
\begin{bmatrix}
V_+ \\ V_+ \\ 0 \\ 0 \\ 0 \\ 0 
\end{bmatrix}
$$
>
> Let us now setup our array to compute it numerically

In [2]:
# we break this into two parts: diagonal and non-diagonal elements

def intialize_diag(N):
    matrix_diag = 4*np.diag(np.ones(N))
    # set the first and last diagonal entries to 3
    matrix_diag[0,0] = 3
    matrix_diag[N-1,N-1] = 3
    return matrix_diag

def gen_minus_ones():
    return np.diag(-1 * np.ones(N))
    
def initialize_non_diag(N):
    # we generate upper negative ones and lower negative ones separately as we will use np roll
    upper_ones = gen_minus_ones()
    upper_ones[:1] = 0 
    matrix_upper_diag = np.roll(upper_ones, -1, axis=0) 
    upper_ones[:2] = 0
    matrix_upper_diag += np.roll(upper_ones, -2, axis=0)
    # this will generate
    # [[0, -1, -1, 0, ... 0],
    #  [0, 0, =1, -1 , ... 0], and so on...

    lower_ones = gen_minus_ones()
    lower_ones[-1:] = 0 
    matrix_lower_diag = np.roll(lower_ones, 1, axis=0) 
    lower_ones[-2:] = 0
    matrix_lower_diag += np.roll(lower_ones, 2, axis=0)

    # we compile the upper and lower negative ones
    matrix_non_diag = matrix_upper_diag + matrix_lower_diag
    return matrix_non_diag

def get_matrix(N):
    matrix = intialize_diag(N) + initialize_non_diag(N)
    return matrix

def const_vector(N, V):
    constant = np.zeros(N)
    constant[0] = V
    constant[1] = V
    return constant

In [3]:
N = 6 # how many junctions
V_source = 5

A = get_matrix(N)
b = const_vector(N, V_source)
print(A, "\n\n", b)

np.linalg.solve(A, b)

[[ 3. -1. -1.  0.  0.  0.]
 [-1.  4. -1. -1.  0.  0.]
 [-1. -1.  4. -1. -1.  0.]
 [ 0. -1. -1.  4. -1. -1.]
 [ 0.  0. -1. -1.  4. -1.]
 [ 0.  0.  0. -1. -1.  3.]] 

 [5. 5. 0. 0. 0. 0.]


array([3.7254902 , 3.43137255, 2.74509804, 2.25490196, 1.56862745,
       1.2745098 ])

4. Now repeat your calculation for the case where there are $N=10\,000$ internal junctions.  This part is not possible using standard tools like the *solve* function.  You need to make use of the fact that the matrix~$\vec{A}$ is banded.  

In [4]:
%time
V_source = 5 # in volts
N = 10000 # how many junctions

A = get_matrix(N)
b = const_vector(N, V_source)
print(A, "\n\n", b)

np.linalg.solve(A, b)

CPU times: total: 0 ns
Wall time: 3.81 μs
[[ 3. -1. -1. ...  0.  0.  0.]
 [-1.  4. -1. ...  0.  0.  0.]
 [-1. -1.  4. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  4. -1. -1.]
 [ 0.  0.  0. ... -1.  4. -1.]
 [ 0.  0.  0. ... -1. -1.  3.]] 

 [5. 5. 0. ... 0. 0. 0.]


array([4.99888228e+00, 4.99861842e+00, 4.99802841e+00, ...,
       1.97158611e-03, 1.38158071e-03, 1.11772227e-03], shape=(10000,))

#### Problem 1 code summary

Include a brief summary (2–3 sentences) at the bottom of your code outlining the purpose of the script and its core algorithm. Focus on explaining why you wrote the code this way and the reasoning behind your implementation choices.

---

### Problem 2 (Statics)

Solve the following matrix problems. Set-up the linear equations that describe the problem then solve them 

Part 1: Suppose you have a hanging mass M supported by two ropes (angled by $\alpha$ and $\beta$ with respect to the ceiling). Make a function that calculates the tension on each of the ropes. Put your function in a python file and call it here in the notebook. Check that the answer by computer matches your own computations.

In [5]:
m = 10
g = 9.81
alpha = np.pi / 3
beta = np.pi / 3

A = np.array([[-np.cos(alpha), np.cos(beta)],
              [np.sin(alpha), np.sin(beta)]])

b = np.array([0, m*g])

np.linalg.solve(A, b)

array([56.63806141, 56.63806141])

In [6]:
import twoStringMass as tsm

tsm.compute_tension(np.pi/3, np.pi/3, 10)

array([56.63806141, 56.63806141])

<del>
Part 2: 
Masses $m_1, m_2, m_3$, and $m_4$ lie on a $2.00$ [m] beam of negligible mass. They are located $0.20, 0.70, 1.10$, and $1.40$ [m] away from the left end of the beam. Determine the masses $m_1, m_2, m_3$, and $m_4$, given the following constraints: 

- The total mass is $8.00$ [kg]
- If a pivot is placed halfway, the beam will balance if a $1.05$ [kg] mass is placed on the right-end of the beam
- If a pivot is placed $1.20$ [m] away from the right end, then the beam would balance if a $550$ [g] mass is placed on the left end of the beam.
- If the system is split midway, the total mass on the left is $1.00$ [kg] heavier than the total mass on the right
</del>

#### Problem 2 code summary

Include a brief summary (2–3 sentences) at the bottom of your code outlining the purpose of the script and its core algorithm. Focus on explaining why you wrote the code this way and the reasoning behind your implementation choices.

---

## Section 3 (Notes)

### Some codes for solving matrix problems

* solving matrix equations ($\bf{A}\vec{x} = \vec{b}$) -> `np.linalg.solve`
* LU-decomposition ($\bf{A} = \bf{L}\bf{U}$) -> `scipy.linalg.lu`
* matrix inversion ($\bf{A}^{-1}$) -> `np.linalg.inv`
* QR-decomposition ($\bf{A} = \bf{Q}\bf{R}$) -> `scipy.linalg.qr`
* eigenvalue problem ($\bf{A}\vec{x} = \lambda \vec{x}$) -> `np.linalg.eig`

Solving matrix problems by themselves isn't difficult. There is an abundance of linear algebra libraries that are ready to use: from the battle-tested ones (the classic [BLAS](https://www.netlib.org/blas/) and [LAPACK](https://www.netlib.org/lapack/)), HPC tools for large problems ([ScaLAPACK](https://netlib.org/scalapack/)), to hardware-accelerated ones often with GPUs ([cuBLAS](https://docs.nvidia.com/cuda/cublas/index.html) and [cuSolver](https://docs.nvidia.com/cuda/cusolver/index.html) for NVIDIA). 

The hardest part is actually composing the matrix. How do you transform a physical problem into a linear algebra problem?

* Circuit: https://personal.math.vt.edu/embree/cmda3606/chapter2.pdf
* Embree [main notes](https://personal.math.vt.edu/embree/cmda3606notes.pdf) + [lab manual](https://personal.math.vt.edu/embree/labman.pdf)

#### Sample Usage (Testing different codes)

In [7]:
A = np.array([[1,0,2],[-2,-1,3],[0,3,5]])
B = np.array([[-2],[1],[-3]])


In [8]:
sigma_z = [[1,0],[0,-1]]
sigma_y = [[0,-1j],[1j,0]]
sigma_x = [[0,1],[1,0]]

In [9]:
ans = np.linalg.solve(sigma_x, sigma_y)
ans = np.linalg.inv(A) @ B


In [10]:
from scipy.linalg import *
p, l, u = lu(A)
p, l, u

(array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ],
        [-0.        ,  1.        ,  0.        ],
        [-0.5       , -0.16666667,  1.        ]]),
 array([[-2.        , -1.        ,  3.        ],
        [ 0.        ,  3.        ,  5.        ],
        [ 0.        ,  0.        ,  4.33333333]]))

### Importing functions from a python file

In [11]:
import samplePackage as sP

In [12]:
testMat = sP.createZerosArray(4,5)

In [13]:
testMat[1] = [1,2,3,4,5]

In [14]:
testMat

array([[0., 0., 0., 0., 0.],
       [1., 2., 3., 4., 5.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### np.roll

In [15]:
## Useful tips. Not required to solve the problems below!

# Suppose you have a Numpy array
x = np.zeros((4,4))
x[1,2] = 5
for row in x:
    print(row)

#rint(x[0,1:3])


# I can move all values to the left/right using roll
x_roll = np.roll(x, 1) # change 1 to -1, what happens? 
#x_roll2 = np.roll(x, -1)
print(x_roll)

x_roll2 = np.roll(x, 2)
print(x_roll2)

[0. 0. 0. 0.]
[0. 0. 5. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 5.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [5. 0. 0. 0.]
 [0. 0. 0. 0.]]
