# AP 155 Lab Exercise
---
## Exercise 5: Matrices

_Instructions_: 
- **Report figure:** No report figure. Points in the report figure will be allocated to the report discussion 
- **Report discussion:**
  - What were the basis linear equations used to set up the matrix in each question of Problem 2?
  - Once you set up the matrices, what function did you use to solve the matrix equation (Could have different answers)? Check the docstring/documentation/other references and summarize the mechanism behind the function 
- **Code**: Complete the code and ensure it is functional, error-free, readable, and efficient (where needed). Include concise Markdown documentation highlighting the critical steps of your algorithm for each problem.

### Student Information
- _Full Name (Last Name, First Name)_: Luarez, Karl Andrei
- _Student No._: 2024-12430
- _Section_: THR-TX-1

### Grading Information (c/o Lab Instructor)
- [Rubrics description link](https://drive.google.com/file/d/1BMSlPot2Mc7XLu0eo4S8I8gLBsIadbCL/view?usp=sharing) (Note: percentages may still be tweaked)

| Criteria | Score | Subtotal |
| --- | --- | --- |
| Report figure | XX | 20 |
| Report discussion | XX | 20|
| Code readability | XX | 20 |
| Code efficiency | XX | 20 | 
| Code appropriateness  | XX | 20 | 
| **TOTAL** | XXX | 100 |

_Date and Time Scored (MM/DD/YYYY HH:MM AM/PM):_:_

---
## Section 1: Report

<!-- ### Report figure

<img src="figures/cat.jpg" alt="Alt text" width=45%> <img src="figures/cat.jpg" alt="Alt text" width=45%>


EDIT ME. See instruction above for what to include. Insert caption here, a short description what the figure illustrates. The syntax in markdown for putting a figure is `![Description](local_file_name.png)` or `<img src="/path/to_image.jpg" alt="Alt text" width=45%>`. Make sure the figure has complete elements.
-->

### Report discussion

1. The basis linear equations were equations of motion (EoM) derived from Newton's Laws are 

$$\begin{align} T_1\cos(\alpha) + T_2\cos(\beta) = 0 \tag{1}\\ 
T_1\sin(\alpha) + T_2\sin(\beta) = Mg \tag{2} \end{align}$$
Where Eq. (1) are EoM along $x$ and Eq. (2) describes EoM along $y$.

2. For both problems, the function used to solve the system of linear equations is np.linalg.solve(). The function works by calculating the exact solution array $\mathbf x$ for the matrix equation $\mathbf A \mathbf b = \mathbf x$ where $\mathbf A$ is square and full rank, i.e. its rows and columns are linearly independent. Its inputs are an an array-like coefficient matrix $A$ and the output array $b$ and its output is the solution array $x$ with identical shape to $b$. The solutions are computed using the LAPACK routine _gesv. The dgesv routine solves real systems $AX=B$ where $A$ is $N \times N$ and $B$ is $N x$ the number of right hand  sides using LU factorization this performs the decomposition $A=PLU$ where $L$ and $U$ are lower and upper triangular matrices and $P$ is the permutation matrix [1]. The factored form is then used to solve an equivalent matrix equation
$$L(Ux)=Pb$$
where $y=Ux$ is unknown. Since L is lower triangular, then the variables $y_i$ can be known immediately. Then $x$ is computed using the upper triangular using the equation
$$Ux=y$$

References:

[1] Netlib. (n.d.). LAPACK routine DGESV: Solve a system of linear equations A * X = B. Netlib LAPACK Working Notes. Retrieved from https://www.netlib.org/lapack/explore-html/d8/da6/group__gesv_ga831ce6a40e7fd16295752d18aed2d541.html
### Other comments
- EDIT ME
- A self reflection can be placed here.
- This portion is not graded.
- You may insert further questions here.


---
## Section 2: Code

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

### Problem 1: (Circuit Analysis)


Consider a long chain of resistors wired up like this:

<img src="reschain.png" alt="Alt text" width=95%>

All the resistors have the same resistance~$R$.  The power rail at the top is at voltage~$V_+=5$V.  The problem is to find the voltages $V_1...V_N$ at the internal points in the circuit.

1. **Using Ohm's law and the Kirchhoff current law**, which says that the total net current flow out of (or into) any junction in a circuit must be zero, show that the voltages $V_1\ldots V_N$ satisfy the equations

$$3V_1 - V_2 - V_3 = V_+ $$
$$-V_1 + 4V_2 - V_3 - V_4 = V_+ $$
      
$$-V_{i-2} - V_{i-1} + 4V_i - V_{i+1} - V_{i+2} = 0 $$

$$-V_{N-3} - V_{N-2} + 4V_{N-1} - V_N = V_- = 0 $$
$$-V_{N-2} - V_{N-1} + 3V_N = V_- = 0 $$

Note: The assignment of $V_-$ is to make the equations symmetric

2. Express these equations in vector form~$A\vec{v} = \vec{w}$ and find the values of the matrix~$A$ and the vector~$\vec{w}$.

3. Write a program to solve for the values of the~$V_i$ when there are $N=6$ internal junctions with unknown voltages.  (Hint: All the values of $V_i$ should lie between zero and $5$V.  If they don't, something is wrong.)

4. Now repeat your calculation for the case where there are $N=10\,000$ internal junctions.  This part is not possible using standard tools like the *solve* function.  You need to make use of the fact that the matrix~$\vec{A}$ is banded.  

For $N=6$ junctions, we have a system of six linear equations:
$$3V_1-V_2-V_3+0+0+0=5V$$

$$-V_1+4V_2-V_3-V_4+0+0=5V$$

$$-V_1-V_2+4V_3-V_4-V_5+0=0$$

$$0-V_2-V_3+4V_4-V_5-V_6=0$$

$$0+0-V_3-V_4+4V_5-V_6=0$$

$$0+0+0-V_4-V_5+3V_6=0$$

Rewriting the system of equations in the form $\mathbf{A}\mathbf{\vec{b}}=\mathbf{\vec{w}}$:

$$\begin{bmatrix}
3 & -1 & -1 & 0 & 0 & 0\\
-1 & 4 & -1 & -1 & 0 & 0\\
-1 & -1 & 4 & -1 & -1 & 0\\
0 & -1 & -1 & 4 & -1 & -1\\
0 & 0 & -1 & -1 & 4 & -1\\
0 & 0 & 0 & -1 & -1 & 3\\
\end{bmatrix} 
\begin{bmatrix} V_1\\V_2\\V_3\\V_4\\V_5\\V_6\end{bmatrix} 
= \begin{bmatrix}5\\5\\0\\0\\0\\0\end{bmatrix}$$ 

In [2]:
# Using np.linalg.solve() to find V_is:

A = np.array([[3,-1,-1,0,0,0],[-1,4,-1,-1,0,0],[-1,-1,4,-1,-1,0],[0,-1,-1,4,-1,-1],[0,0,-1,-1,4,-1],[0,0,0,-1,-1,3]])
w = np.array([5,5,0,0,0,0])

Vs = np.linalg.solve(A,w)

for i, Vi in enumerate (Vs, start = 1):
  print(f"V_{i} = {Vi}")

V_1 = 3.725490196078432
V_2 = 3.4313725490196085
V_3 = 2.745098039215687
V_4 = 2.254901960784314
V_5 = 1.5686274509803926
V_6 = 1.274509803921569


In general, to solve for a system with $N$ equations, we use the fact that the coefficient matrix $\mathbf A$ is a banded matrix. We recreate the $N \times N$ matrix $\mathbf A$ for $N$ equations and use np.linalg.solve() to find solutions to that system.

In [3]:
N = 10000

def solve_banded(N):
  # We create a 5xN array since A has 5 non-zero diagonals
  diag_A = np.zeros((5, N)) 
  diag_A[0,2:] = -1 # 2nd UD (upper diagonal)
  diag_A[1,1:] = -1 # 1st UD
  diag_A[2,:] = 4 # Main Diagonal
  diag_A[3, :-1] = -1 # 1st LD (lower diagonal)
  diag_A[4, :-2] = -1 # 2nd LD
  # The (0,0) and (N,N) element:
  diag_A[2,0] = 3
  diag_A[2,-1] = 3
  # creating the output vector w
  w = np.zeros(N)
  w[0] = 5
  w[1] = 5
  
  A = np.zeros((N,N)) # create an NxN storage
  for j in range(N): # iterate each column with index j
    l = 2 # no. of lower diagonal bands
    u = 2 # no. of upper diagonal bands
    imin = max(0, j - u) # row elements above the main diagonal
    imax = min(N, j + l + 1) # row elements below the main diagonal
    for i in range(imin, imax): #iterate over each column with index j
        A[i, j] = diag_A[u + i - j, j] # copy elements from the diag_A into the nonzero diagonals of the coefficient matrix A
            
  Vs = np.linalg.solve(A, w)
  return Vs, A

# For N = 1000
Vs, A = solve_banded(N)
print("Coefficient matrix A:")
print(A)
print("Vi:")
print(Vs)

Coefficient matrix A:
[[ 3. -1. -1. ...  0.  0.  0.]
 [-1.  4. -1. ...  0.  0.  0.]
 [-1. -1.  4. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  4. -1. -1.]
 [ 0.  0.  0. ... -1.  4. -1.]
 [ 0.  0.  0. ... -1. -1.  3.]]
Vi:
[4.99888228e+00 4.99861842e+00 4.99802841e+00 ... 1.97158611e-03
 1.38158071e-03 1.11772227e-03]


#### Problem 1 code summary

Include a brief summary (2–3 sentences) at the bottom of your code outlining the purpose of the script and its core algorithm. Focus on explaining why you wrote the code this way and the reasoning behind your implementation choices.

---

The script attempts to solve the system of equations for $N=6$ junctions then extend it for some arbitrary $N$ to solve a system of $N=10000$ junctions using the fact that the coefficient matrix $\mathbf A$ is a banded matrix with $-1$ elements in the first two upper and lower diagonals and 4 as elements of its main diagonal, with 3 as its (0,0) and (N,N) elements. It first creates an array of the non-zero diagonal then makes an NxN storage and iterates over the column and elements to copy the diagonal entries such that an NxN banded matrix is made. Then it uses np.linalg.solve() to find the $V_{i}$'s for any number of junctions.

### Problem 2 (Statics)


Solve the following matrix problems. Set-up the linear equations that describe the problem then solve them 

Part 1: Suppose you have a hanging mass M supported by two ropes (angled by $\alpha$ and $\beta$ with respect to the ceiling). Make a function that calculates the tension on each of the ropes. Put your function in a python file and call it here in the notebook. Check that the answer by computer matches your own computations.

<del>Part 2: 
Masses $m_1, m_2, m_3$, and $m_4$ lie on a $2.00$ [m] beam of negligible mass. They are located $0.20, 0.70, 1.10$, and $1.40$ [m] away from the left end of the beam. Determine the masses $m_1, m_2, m_3$, and $m_4$, given the following constraints: 
<del>
- <del>The total mass is $8.00$ [kg]
- <del>If a pivot is placed halfway, the beam will balance if a $1.05$ [kg] mass is placed on the right-end of the beam
- <del>If a pivot is placed $1.20$ [m] away from the right end, then the beam would balance if a $550$ [g] mass is placed on the left end of the beam.
- <del>If the system is split midway, the total mass on the left is $1.00$ [kg] heavier than the total mass on the right

Part 1

Since the mass is at rest, then the net forces on it must be zero along $x$ and $y$, i.e.

Along $x$:

$$T_1\cos(\alpha) + T_2\cos(\beta) = 0$$

Along $y$:
$$T_1\sin(\alpha) + T_2\sin(\beta) = Mg$$

where $T_1 \space \& \space T_2$ is the tension on the string. Rewriting the equation in vector form  $\mathbf{A}\mathbf{\vec{b}}=\mathbf{\vec{w}}$:

$$\begin{bmatrix} 
\cos(\alpha) &\cos(\beta) \\
\sin(\alpha) & \sin(\beta) 
\end{bmatrix} 
\begin{bmatrix}
T_1\\
T_2\\
\end{bmatrix}
= \begin{bmatrix}
0\\ Mg
\end{bmatrix}$$

Then we call the calc_T() function in the karlboro python file to find T1 and T2

In [4]:
import karlboro as yb
alpha = 30
beta = 60
M = 10
T = yb.calc_T(alpha, beta, M)

T1=-98.10000000000002
T2=169.9141842225069


#### Problem 2 code summary

Include a brief summary (2–3 sentences) at the bottom of your code outlining the purpose of the script and its core algorithm. Focus on explaining why you wrote the code this way and the reasoning behind your implementation choices.

---

The code solves the statics problem in Part 1 using a function defined in a different python file to avoid putting lengthy functions in the main python notebook. It is solved by first defining the equations of motion and then rewriting it into the form $\mathbf{A}\mathbf{\vec{b}}=\mathbf{\vec{w}}$. Then, the calc_T() function was created that takes in angle and mass inputs and uses the np.linalg.solve() function using the coefficient matrix and output vectors to find the tension on both strings.

## Section 3 (Notes)

In [5]:
np.linalg.solve?

Signature: np.linalg.solve(a, b)
Docstring:
Solve a linear matrix equation, or system of linear scalar equations.

Computes the "exact" solution, `x`, of the well-determined, i.e., full
rank, linear matrix equation `ax = b`.

Parameters
----------
a : (..., M, M) array_like
    Coefficient matrix.
b : {(..., M,), (..., M, K)}, array_like
    Ordinate or "dependent variable" values.

Returns
-------
x : {(..., M,), (..., M, K)} ndarray
    Solution to the system a x = b.  Returned shape is identical to `b`.

Raises
------
LinAlgError
    If `a` is singular or not square.

See Also
--------
scipy.linalg.solve : Similar function in SciPy.

Notes
-----

.. versionadded:: 1.8.0

Broadcasting rules apply, see the `numpy.linalg` documentation for
details.

The solutions are computed using LAPACK routine ``_gesv``.

`a` must be square and of full-rank, i.e., all rows (or, equivalently,
columns) must be linearly independent; if either is not true, use
`lstsq` for the least-squares best "solutio

### Some codes for solving matrix problems

* solving matrix equations ($\bf{A}\vec{x} = \vec{b}$) -> `np.linalg.solve`
* LU-decomposition ($\bf{A} = \bf{L}\bf{U}$) -> `scipy.linalg.lu`
* matrix inversion ($\bf{A}^{-1}$) -> `np.linalg.inv`
* QR-decomposition ($\bf{A} = \bf{Q}\bf{R}$) -> `scipy.linalg.qr`
* eigenvalue problem ($\bf{A}\vec{x} = \lambda \vec{x}$) -> `np.linalg.eig`

Solving matrix problems by themselves isn't difficult. There is an abundance of linear algebra libraries that are ready to use: from the battle-tested ones (the classic [BLAS](https://www.netlib.org/blas/) and [LAPACK](https://www.netlib.org/lapack/)), HPC tools for large problems ([ScaLAPACK](https://netlib.org/scalapack/)), to hardware-accelerated ones often with GPUs ([cuBLAS](https://docs.nvidia.com/cuda/cublas/index.html) and [cuSolver](https://docs.nvidia.com/cuda/cusolver/index.html) for NVIDIA). 

The hardest part is actually composing the matrix. How do you transform a physical problem into a linear algebra problem?

* Circuit: https://personal.math.vt.edu/embree/cmda3606/chapter2.pdf
* Embree [main notes](https://personal.math.vt.edu/embree/cmda3606notes.pdf) + [lab manual](https://personal.math.vt.edu/embree/labman.pdf)

#### Sample Usage (Testing different codes)

In [6]:
A = np.array([[1,0,2],[-2,-1,3],[0,3,5]])
B = np.array([[-2],[1],[-3]])


In [7]:
sigma_z = [[1,0],[0,-1]]
sigma_y = [[0,-1j],[1j,0]]
sigma_x = [[0,1],[1,0]]

In [8]:
ans = np.linalg.solve(sigma_x, sigma_y)
ans = np.linalg.inv(A) @ B


In [9]:
from scipy.linalg import *
p, l, u = lu(A)
p, l, u

(array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ],
        [-0.        ,  1.        ,  0.        ],
        [-0.5       , -0.16666667,  1.        ]]),
 array([[-2.        , -1.        ,  3.        ],
        [ 0.        ,  3.        ,  5.        ],
        [ 0.        ,  0.        ,  4.33333333]]))

### Importing functions from a python file

In [10]:
import samplePackage as sP

In [11]:
testMat = sP.createZerosArray(4,5)

In [12]:
testMat[1] = [1,2,3,4,5]

In [13]:
testMat

array([[0., 0., 0., 0., 0.],
       [1., 2., 3., 4., 5.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### np.roll

In [14]:
## Useful tips. Not required to solve the problems below!

# Suppose you have a Numpy array
x = np.zeros((4,4))
x[1,2] = 5
for row in x:
    print(row)

#rint(x[0,1:3])


# I can move all values to the left/right using roll
#x_roll = np.roll(x, 1) # change 1 to -1, what happens? 
x_roll = np.roll(x, 1)
print(x_roll)

x_roll2 = np.roll(x, 2)
print(x_roll2)

[0. 0. 0. 0.]
[0. 0. 5. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 5.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [5. 0. 0. 0.]
 [0. 0. 0. 0.]]
